### ISSUE TITLE
feat: separate cmdSteps into installCmdSteps and uninstallCmdSteps

### ISSUE THREAD

**Issue by ntorga** [speedianet/os#51]

**Comment by polillomm** [comment]
Even with the separation of commands, it will still be necessary to refactor how the repository removes files related to the installation. This is because it currently does not distinguish between the installation of a specific _vhost_ and whether a directory belongs to another _vhost_.

**Comment by polillomm** [comment]
A validation has been added to ensure that a marketplace item is installed in the selected installation directory. This prevents the need for backups or other methods to replace one installation with another.

From now on, installation directories that already have a marketplace item installed will not accept a new installation. To replace the current item, the existing marketplace item must be uninstalled before installing the new one.

**Comment by polillomm** [comment]
The installation of **Drupal** and **Laravel** has a specific peculiarity for installations with routing typically managed by `.htaccess` in subdirectories, such as **Drupal** using `/web` and **Laravel** using `/public`. To correctly reflect these characteristics in the **NGINX** mapping configuration, a _symlink_ is created from the virtual host directory to the installation subdirectory (e.g., `/web` or `/public`). This ensures the root directory of the virtual host performs the correct routing required by these installations.
