### ISSUE TITLE
feat: .htaccess auto reload

### ISSUE THREAD

**Issue by ntorga** [speedianet/os#56]
OpenLiteSpeed only read .htaccess on reload, thus we need to monitor for changes on .htaccess and reload OLS.

- A 2 to 3 minutes tick on Go to run a infra for checking if any .htaccess has changed on /app/html directory;
- Recommend using find with mtime to check for the modified files and -name for the name filtering, maybe 7 for depth is ok;
- Reload OLS once any modified file was found;
- After finishing the feature, recommend checking if .htaccess is being reload after OLS reload by putting a deny all on some .htaccess file and checking with curl if you get a 403 for example.

**Comment by polillomm** [comment]
The same watchdog implementation used for SSL validation and replacement was applied to create the `.htaccess` watchdog.
