### ISSUE TITLE
feat: opensearch support

### ISSUE THREAD

**Issue by ntorga** [speedianet/os#63]
OpenSearch is required by Magento and is quite useful for metrics, logs and well, search. The /database/ endpoint should be able to manage the indexes for simple cleanup operations since most people will be using OS Dashboard.

---

How about using slog.Debug on marketplace and on services since you'll be adding a new service and a new marketplace item?

---

You may need to install Java. I would take the opportunity to add java to the create-installable using Mise.

**Comment by ntorga** [comment]
How about using slog.Debug on marketplace and on services since you'll be adding a new service and a new marketplace item?

**Comment by polillomm** [comment]
The tasks referenced in this are #59 and #129.
